### ISSUE TITLE
3.x compatibility?

### ISSUE THREAD

**Issue by rgaufman** [Neurone/reMarkable#2]
Is this compatible with 3.x?

**Comment by Neurone** [comment]
Hi @rgaufman , unfortunately not in the current state. I think the optimization to reduce battery consumption has reduced the frequency of updates of the UI so, even if image files are swapped live, they are not reloaded in the UI.

Also, to save the space reserved to the system (`/usr/share/remarkable/`, that can also be overwritten with upgrades) I use the user disk space (`/home/root/customization/images/`), but now the UI is loaded - most of the time - before mounting the user space, so it does not load the new images.

The only way to change reliably those images at the moment is to overwrite the original files - after a backup - every time you want to change them.

I'll give this a try if I can update the scripts to work with the 3.x.

**Comment by Neurone** [comment]
Done! The scripts is now compatible with `3.4.x` ;) We still have the problem we need to restart to see the new suspend image, but for the rest everything is working now.

**Comment by rgaufman** [comment]
Amazing, thank you, will give it a try!
